CREATE TABLE IF NOT EXISTS event (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY_KEY,
    name VARCHAR(100) NOT NULL,
    organizer_id BIGINT NOT NULL FOREIGN KEY REFERENCES club(id),
    date TIMESTAMP NOT NULL,
    place VARCHAR(100) NOT NULL
);