CREATE TABLE IF NOT EXISTS event (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    organizer_id BIGINT,
    date TIMESTAMP NOT NULL,
    place VARCHAR(100) NOT NULL,
    FOREIGN KEY (organizer_id) REFERENCES club(id)
);