CREATE TABLE IF NOT EXISTS event_meta (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY_KEY,
    event_id BIGINT NOT NULL FOREIGN KEY REFERENCES event(id),
    key VARCHAR(50) NOT NULL,
    value VARCHAR(500) NOT NULL
);