CREATE TABLE IF NOT EXISTS event_meta (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    event_id BIGINT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    FOREIGN KEY (event_id) REFERENCES event(id)
);