name: Deploy to Server

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Prod Server
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: .
          scp_target: ~/svc/gibz-m133/
          before_script: |
            mkdir -p ~/svc/gibz-m133/
            cd ~/svc/gibz-m133/
            docker-compose down &
          after_script: |
            cd ~/svc/gibz-m133/ && docker-compose up --build -d